
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label serverLabel;

	private global::Gtk.Label nicknameLabel;

	private global::Gtk.Entry serverIp;

	private global::Gtk.Entry Nickname;

	private global::Gtk.Button Connect;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.serverLabel = new global::Gtk.Label();
		this.serverLabel.Name = "serverLabel";
		this.serverLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Server IP:");
		this.fixed1.Add(this.serverLabel);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.serverLabel]));
		w1.X = 16;
		w1.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.nicknameLabel = new global::Gtk.Label();
		this.nicknameLabel.Name = "nicknameLabel";
		this.nicknameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Nickname:");
		this.fixed1.Add(this.nicknameLabel);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.nicknameLabel]));
		w2.X = 9;
		w2.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.serverIp = new global::Gtk.Entry();
		this.serverIp.CanFocus = true;
		this.serverIp.Name = "serverIp";
		this.serverIp.IsEditable = true;
		this.serverIp.InvisibleChar = '•';
		this.fixed1.Add(this.serverIp);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.serverIp]));
		w3.X = 101;
		w3.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Nickname = new global::Gtk.Entry();
		this.Nickname.CanFocus = true;
		this.Nickname.Name = "Nickname";
		this.Nickname.IsEditable = true;
		this.Nickname.InvisibleChar = '•';
		this.fixed1.Add(this.Nickname);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Nickname]));
		w4.X = 101;
		w4.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Connect = new global::Gtk.Button();
		this.Connect.CanFocus = true;
		this.Connect.Name = "Connect";
		this.Connect.UseUnderline = true;
		this.Connect.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.fixed1.Add(this.Connect);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Connect]));
		w5.X = 288;
		w5.Y = 15;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Connect.Clicked += new global::System.EventHandler(this.OnConnectClicked);
	}
}
